version: '2'
services:
  ws-service:
    image: ws-service:latest
    network_mode: "bridge"
    ports:
      - "4100:4100"
    environment:
      - ENV=default
    command: /bin/ws-service
    volumes:
      - ./logs:/logs
      - ./configs:/configs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"